// <auto-generated />
using System;
using Cines_Flagg.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cines_Flagg.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20230714235454_Nueva3")]
    partial class Nueva3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cines_Flagg.Models.Funcion", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CantClientes")
                        .HasColumnType("int");

                    b.Property<double>("Costo")
                        .HasColumnType("float");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("date");

                    b.Property<int>("idPelicula")
                        .HasColumnType("int");

                    b.Property<int>("idSala")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("idPelicula");

                    b.HasIndex("idSala");

                    b.ToTable("Funciones", (string)null);
                });

            modelBuilder.Entity("Cines_Flagg.Models.Pelicula", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Duracion")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Poster")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Sinopsis")
                        .HasColumnType("varchar(200)");

                    b.HasKey("ID");

                    b.ToTable("Peliculas", (string)null);
                });

            modelBuilder.Entity("Cines_Flagg.Models.Sala", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Capacidad")
                        .HasColumnType("int");

                    b.Property<string>("Ubicacion")
                        .HasColumnType("varchar(100)");

                    b.HasKey("ID");

                    b.ToTable("Sala", (string)null);
                });

            modelBuilder.Entity("Cines_Flagg.Models.Usuario", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Apellido")
                        .HasColumnType("varchar(50)");

                    b.Property<bool?>("Bloqueado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("0");

                    b.Property<double?>("Credito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValueSql("0");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<bool?>("EsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("0");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<int?>("IntentosFallidos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("0");

                    b.Property<string>("Mail")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nombre")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .HasColumnType("varchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Apellido = "Gomez",
                            Bloqueado = false,
                            Credito = 0.0,
                            DNI = "45678964",
                            EsAdmin = true,
                            FechaNacimiento = new DateTime(1974, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IntentosFallidos = 0,
                            Mail = "m@mail",
                            Nombre = "Obdulio",
                            Password = "123"
                        });
                });

            modelBuilder.Entity("Cines_Flagg.Models.UsuarioFuncion", b =>
                {
                    b.Property<int>("idUsuario")
                        .HasColumnType("int");

                    b.Property<int>("idFuncion")
                        .HasColumnType("int");

                    b.Property<int>("cantidadCompra")
                        .HasColumnType("int");

                    b.HasKey("idUsuario", "idFuncion");

                    b.HasIndex("idFuncion");

                    b.ToTable("UF");
                });

            modelBuilder.Entity("Cines_Flagg.Models.Funcion", b =>
                {
                    b.HasOne("Cines_Flagg.Models.Pelicula", "MiPelicula")
                        .WithMany("MisFunciones")
                        .HasForeignKey("idPelicula")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cines_Flagg.Models.Sala", "MiSala")
                        .WithMany("MisFunciones")
                        .HasForeignKey("idSala")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MiPelicula");

                    b.Navigation("MiSala");
                });

            modelBuilder.Entity("Cines_Flagg.Models.UsuarioFuncion", b =>
                {
                    b.HasOne("Cines_Flagg.Models.Funcion", "MiFuncion")
                        .WithMany("UsuarioFuncion")
                        .HasForeignKey("idFuncion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cines_Flagg.Models.Usuario", "MiUsuario")
                        .WithMany("UsuarioFuncion")
                        .HasForeignKey("idUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MiFuncion");

                    b.Navigation("MiUsuario");
                });

            modelBuilder.Entity("Cines_Flagg.Models.Funcion", b =>
                {
                    b.Navigation("UsuarioFuncion");
                });

            modelBuilder.Entity("Cines_Flagg.Models.Pelicula", b =>
                {
                    b.Navigation("MisFunciones");
                });

            modelBuilder.Entity("Cines_Flagg.Models.Sala", b =>
                {
                    b.Navigation("MisFunciones");
                });

            modelBuilder.Entity("Cines_Flagg.Models.Usuario", b =>
                {
                    b.Navigation("UsuarioFuncion");
                });
#pragma warning restore 612, 618
        }
    }
}
